eureka:
  client:
    serviceUrl:
      defaultZone: http://119.29.208.119:8761/eureka/
# server:
#   port: 8762
spring:
  application:
    name: service-zuul
zuul:
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000
  routes:
    #路由转发
    api-basicS:
      path: /api-basicS/**
      url: http://119.29.79.92:8763
    classify-service:
      path: /classify-service/**
      url: http://119.29.208.119:8765
#  重定向时隐藏真实端口地址
  add-host-header: true
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
multipart:
  maxFileSize: 10Mb
  maxRequestSize: 50Mb
